### ISSUE TITLE
postNewRoom() saving nil data

### ISSUE THREAD

**Issue by nazardz** [catinsurance/IsaacSaveManager#1]
mod users told me he fixed it by checking if it's 'nil', so I'm assume it somehow saved nil data.
line 469:
hourglassBackup.run = SaveManager.Utility.DeepCopy(dataCache.game.run)

**Comment by catinsurance** [comment]
I'm unsure what the issue is. If it's saving nil, please provide an affected save file. If it is erroring, please provide a log file with the error.

The save retrieving functions like GetRunSave have the capability to return nil if there is no data to load, such as if data hasn't been loaded from file yet. You can use `.IsLoaded()` on the save manager to check if file data has loaded, and you should also check to make sure the specific save you want to retrieve is not nil before using it.
